import Home from "./pages/Home"
import About from "./pages/About"
import Skills from "./pages/Skills"
import Projects from "./pages/Projects"
import CreativeFrame from "./pages/CreativeFrame"
import Header from "./header/Header"
import AboutSite from "./pages/AboutSite"
import OtherProjects from "./project/OtherProjects"
import Login from "./creative frame/Login"
import Upload from "./creative frame/Upload"
export { Home, About, Skills, Projects, CreativeFrame, Header, AboutSite, OtherProjects, Login, Upload }